package com.mediSync.project.insurance.vo;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@NoArgsConstructor
public class ClaimRequest {
    private Long claimId;
    private Long recordId;
    private String insurerCode;
    private BigDecimal claimAmount;
    private String status;
    private boolean autoGenerated;
    private LocalDateTime  createdAt;
    private BigDecimal payoutAmount;
    private LocalDateTime paidDate;
    private LocalDateTime updatedAt;
    private Long patientId;
}
