package com.mediSync.project.insurance.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.math.BigDecimal;
import java.util.Map;

@Mapper
public interface ClaimMapper {
    int insertClaim(@Param("recordId") Long recordId,
                    @Param("insurerCode") String insurerCode,
                    @Param("claimAmount") BigDecimal claimAmount,
                    @Param("autoGenerated") int autoGenerated);
    int updateClaimResponse(@Param("claimId") Long claimId,
                            @Param("paidAmount") BigDecimal paidAmount,
                            @Param("resultCode") String resultCode,
                            @Param("message") String message);
    int insertClaimLog(@Param("claimId") Long claimId,
                       @Param("status") String status,
                       @Param("message") String message);
    Map<String,Object> findLastClaimByRecord(@Param("recordId") Long recordId);
    int insertClaimResponse(@Param("claimId") Long claimId,
                            @Param("paidAmount") BigDecimal paidAmount,
                            @Param("resultCode") String resultCode,
                            @Param("message") String message);

}
